(() => {
  'use strict';
  const $ = selector => document.querySelector(selector);
  const engine=window.ARIA_DEMO_ENGINE, data=window.ARIA_DEMO_DATA, proof=window.ARIA_EVIDENCE;
  const storageKey='aria-tablet-demo-v3-en';
  let state=engine.fresh(), query='';
  try {const saved=JSON.parse(localStorage.getItem(storageKey)); if(saved?.schema===3 && saved.step>=0 && saved.step<=5 && [0,1,2].includes(saved.revision)) state={...state,...saved};} catch {}
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const button=(action,label,value='',kind='secondary',disabled=false)=>`<button type="button" class="${kind}" data-action="${action}" data-value="${value}" ${['ROLE','AI','DEPTH'].includes(action)?`aria-pressed="${kind==='active'}"`:''} ${disabled?'disabled':''}>${label}</button>`;
  const steps=['Task','Context','Plan','Change','Checks','Readiness'];
  const intro=(index,title,text)=>`<header class="screen-heading"><span class="eyebrow">${index}</span><h1>${title}</h1><p>${text}</p></header>`;
  const flag=(text,kind='neutral')=>`<div class="notice ${kind}" role="status">${text}</div>`;
  function save(){try{localStorage.setItem(storageKey,JSON.stringify(state));}catch{}}
  function dispatch(action){const scroll=$('#screen').scrollTop;state=engine.reduce(state,action);save();render();if(!['STEP','VIEW','RESET'].includes(action.type))$('#screen').scrollTop=scroll;}
  function stageView(){
    const version=state.revision===0?'Initial version':state.revision===1?'Fixed version':'File changed after verification';
    switch(state.step){
      case 0: return intro('01 / TASK','What needs to change?','Add a permission check: only an administrator may change a request status.')+`<div class="two-columns"><article class="panel"><span class="eyebrow">TASK FOR THE TEAM AND AI</span><h2>Restrict request status changes</h2><p>An administrator moves a request from “New” to “In progress”. A user with read-only access must not change its state.</p><div class="criteria">${['Administrator is allowed','Read-only user is denied'].map((t,i)=>`<button type="button" data-action="CRITERION" data-value="${i}" class="choice-row ${state.criterion===i?'selected':''}" aria-pressed="${state.criterion===i}"><span>0${i+1}</span><strong>${t}</strong><span>→</span></button>`).join('')}</div></article><article class="panel accent"><span class="eyebrow">SELECTED CRITERION</span><h2>${state.criterion===0?'Change allowed':'Change denied'}</h2><p>${state.criterion===0?'After the administrator acts, the status must become “In progress”.':'After the read-only user tries, the status must remain “New”. The system reports that permission is denied.'}</p><div class="mini-flow"><span>${state.criterion===0?'Administrator':'Read only'}</span><b>→</b><span>${state.criterion===0?'In progress':'Denied'}</span></div><p class="small">Select a criterion on the left. A.R.I.A. links the task criteria to checks of the result.</p></article></div><div class="stage-action">${state.taskLocked?flag('Both acceptance criteria are saved.','good'):button('LOCK_TASK','Save acceptance criteria','','primary')}<span>The team agrees on what “done” means before work begins.</span></div>`;
      case 1: {
        const components={rights:{name:'User permissions',question:'Who can change the status?',text:'The function must distinguish an administrator from a read-only user. The missing role check causes the defect.',path:'role → admin / viewer'},code:{name:'Status update function',question:'Where is the change made?',text:'This example changes one function, change_status. It checks the user’s permission before writing a new status.',path:'backend/service.py → change_status'},data:{name:'Request state',question:'What must remain unchanged?',text:'An allowed action changes the status. A denied action must leave the request state unchanged.',path:'request.status → new / in_progress'}};
        const c=components[state.component];
        return intro('02 / CONTEXT','Which parts does the task affect?','Select a component to see its role and what needs to be checked.')+`<div class="two-columns"><article class="panel"><span class="eyebrow">CHANGE SCOPE</span><div class="component-map">${Object.entries(components).map(([id,v],i)=>`<button type="button" class="component ${state.component===id?'selected':''}" data-action="COMPONENT" data-value="${id}" aria-pressed="${state.component===id}"><span>0${i+1}</span><strong>${v.name}</strong><small>Open →</small></button>`).join('')}</div><p>Permissions → update function → request state.</p><div class="role-note"><strong>What does A.R.I.A. do here?</strong><p>The project map helps identify the change scope and related risks. The code determines the actual behavior.</p></div></article><article class="panel accent"><span class="eyebrow">${c.name}</span><h2>${c.question}</h2><p>${c.text}</p><div class="file-path">${c.path}</div></article></div>`;
      }
      case 2: return intro('03 / PLAN','How will the task be completed?','The task covers a code change and checks of both acceptance criteria. Select an AI tool to see its role.')+`<div class="two-columns"><article class="panel"><div class="task-row"><span>01</span><div><strong>Add a permission check</strong><p>Check the role before changing the request state.</p></div><span class="pill">${state.revision>0?'Fix available':'Code'}</span></div><div class="task-row"><span>02</span><div><strong>Check both user roles</strong><p>An allowed action, and a denied action that leaves the data unchanged.</p></div><span class="pill">${state.check?.passed?'Passed':'Checks'}</span></div><div class="task-row"><span>03</span><div><strong>Check readiness</strong><p>Match the result to the current file version.</p></div><span class="pill">Acceptance</span></div><div class="stage-action">${state.planReady?flag('The plan is saved for this demo.','good'):button('PLAN','Save the plan','','primary')}</div></article><article class="panel accent"><span class="eyebrow">WHO DOES THE WORK</span><div class="segmented">${button('AI','Codex','codex',state.ai==='codex'?'active':'')}${button('AI','Claude Code','claude',state.ai==='claude'?'active':'')}</div><h2>${state.ai==='codex'?'Codex receives the project rules':'Claude Code receives rules and a protection hook'}</h2><p>AI analyzes and changes the code. A.R.I.A. provides context, organizes the workflow and checks the evidence needed to complete the task.</p><p class="small">This selector explains the integrations. No live AI tool is connected to this HTML demo.</p></article></div>`;
      case 3: return intro('04 / CHANGE','Try changing the status.','Select a user and choose “Start work”. Then add the permission check and try again.')+`<div class="two-columns"><article class="panel product-panel"><div class="panel-top"><span class="eyebrow">REQUEST #42</span><span class="version-badge">${version}</span></div><h2>Service request processing</h2><div class="request-status ${state.requestStatus==='in_progress'?'in-progress':''}"><span>Status</span><strong>${state.requestStatus==='new'?'New':'In progress'}</strong></div><label class="control-label">Act as</label><div class="segmented">${button('ROLE','Administrator','admin',state.role==='admin'?'active':'')}${button('ROLE','Read only','viewer',state.role==='viewer'?'active':'')}</div><div class="action-row">${button('TRY_STATUS','Start work →','','primary')}${button('RESET_REQUEST','Reset status')}</div>${state.attempt?flag(esc(state.attempt.text),state.attempt.bug?'warn':state.attempt.allowed?'good':'neutral'):flag('Use the button to test the selected version.')}</article><article class="panel accent"><span class="eyebrow">CODE CHANGE</span><h2>${state.revision===0?'No permission check yet':'Role check added'}</h2><p>${state.revision===0?'The function accepts an update from any user. Try the read-only role: the status changes, even though the task criteria prohibit it.':'The function checks the role first. A read-only user is denied, and the status stays unchanged.'}</p>${state.revision===0?button('FIX','Add permission check','','primary'):flag('The fixed version is available for verification.','good')}<details class="inline-details"><summary>View the code for this version</summary><pre>${esc(state.revision===0?proof.beforeCode:proof.afterCode+(state.revision===2?'\n# changed after verification\n':''))}</pre></details><p class="small">You control a local model of the module’s behavior. The checks for this change were actually executed through the A.R.I.A. core.</p></article></div>`;
      case 4: {
        const current=state.check&&state.check.revision===state.revision;
        const record=current?state.check.record:null;
        return intro('05 / CHECKS','What did the checks show?','Open the recorded result for the current version. A.R.I.A. recorded the command, its output and the code state.')+`<div class="two-columns"><article class="panel"><div class="panel-top"><span class="eyebrow">TWO ACCEPTANCE CRITERIA</span><span class="version-badge">${version}</span></div>${['Administrator changes the status','Read-only user is denied'].map((t,i)=>`<div class="check-row"><span class="check-icon ${record?(record==='after'||i===0?'passed':'failed'):''}">${record?(record==='after'||i===0?'✓':'×'):'○'}</span><div><strong>${t}</strong><p>${record?(record==='after'||i===0?'Criterion verified':'Violation: status changed without permission'):'Result not opened yet'}</p></div></div>`).join('')}<div class="action-row">${button('CHECK',state.revision===2?'Check for a new result':'Open this version’s result','','primary')}${button('MATERIALS','Run evidence')}</div>${state.revision===2?flag('The file changed after verification. No new check is recorded for this version.','warn'):record?flag(record==='after'?'The executed checks confirm both criteria.':'The initial version failed the permission check.',record==='after'?'good':'warn'):''}</article><article class="panel output-panel"><span class="eyebrow">OUTPUT FROM THE EXECUTED COMMAND</span>${record?`<span class="record-stamp">Recorded on October 4, 2026</span><pre>${esc(record==='before'?proof.beforeOutput:proof.afterOutput)}</pre><div class="output-summary">${record==='after'?'Checks passed':'Checks failed'}</div>`:'<div class="empty-state"><span>○</span><h2>Open a result</h2><p>The exact output of the recorded A.R.I.A. run will appear here.</p></div>'}<p class="small">This HTML displays a recorded run. The Python command does not execute on the tablet.</p></article></div>`;
      }
      case 5: {
        const d=state.decision;
        return intro('06 / READINESS','Can the result be accepted?','Check the completion criteria. Then change the file after verification and see what happens.')+`<div class="two-columns"><article class="panel"><span class="eyebrow">WORK STATUS</span><div class="summary-row"><span>Criteria and plan</span><strong>${state.taskLocked&&state.planReady?'Saved':'Not saved'}</strong></div><div class="summary-row"><span>Code</span><strong>${version}</strong></div><div class="summary-row"><span>Checks</span><strong>${!state.check?'No result':state.check.revision!==state.revision?'Result is outdated':state.check.passed?'Both criteria met':'Defect found'}</strong></div><div class="action-row">${button('READY','Check readiness','','primary')}${button('MATERIALS','Open evidence')}</div><div class="challenge"><strong>Try the outdated-result safeguard</strong><p>After the checks pass, change the file and request acceptance again.</p>${state.revision===2?button('RESTORE','Restore the verified version'):button('EDIT','Change the file after verification','','secondary',!state.check?.passed||state.revision!==1)}</div></article><article class="panel decision-panel ${d?.kind==='prepared'?'good-panel':''}"><span class="eyebrow">DECISION</span>${d?`<span class="decision-icon">${d.kind==='prepared'?'✓':'×'}</span><h2>${d.title}</h2><p>${d.reason}</p>${d.kind==='prepared'?'<p class="small">This run checked the module. A complete cycle with AI, independent review and final closure was not performed.</p>':''}`:'<div class="empty-state"><span>?</span><h2>Request a readiness check</h2><p>The decision depends on the actions you take in the demo.</p></div>'}</article></div>`;
      }
      default:return '';
    }
  }
  function aboutView(){return intro('ABOUT A.R.I.A.','A.R.I.A. organizes product development with AI.','A framework we developed: a connected set of tools and rules for building software products.')+`<div class="about-grid"><article class="panel"><h2>What does A.R.I.A. do?</h2><p>It preserves project state, links requirements to tasks and checks, tracks contributors and checks the evidence for completing work.</p><div class="role-note"><strong>Who writes the code?</strong><p>A developer or an AI agent. A.R.I.A. provides context and rules, runs approved checks and records their results.</p></div>${button('GO','Try the task yourself →',0,'primary')}</article><article class="panel accent"><h2>What does the team gain?</h2><ul class="plain-list"><li>A clear view of the work status and the next step.</li><li>Agreed completion criteria.</li><li>Tracking of permissions, responsibilities and overlapping work.</li><li>A way to examine the evidence behind acceptance.</li></ul>${button('VIEW','Explore features','functions')}</article></div><div class="process-strip">${data.process.map((p,i)=>`<button type="button" data-action="GO" data-value="${[0,1,3,4,5][i]}"><span>0${i+1}</span><strong>${p.title}</strong><small>${p.who}</small></button>`).join('')}</div>`;}
  function teamView(){return intro('TEAMWORK','Two contributors. One file.','Try assigning the same scope to developer A, then to B. Release it and try again.')+`<div class="team-scope"><span>WORK SCOPE</span><strong>Status update function</strong><span class="pill">${state.lease?'Assigned to: '+state.lease:'Available'}</span></div><div class="two-columns">${['A','B'].map(a=>`<article class="panel ${state.lease===a?'accent':''}"><span class="eyebrow">CONTRIBUTOR ${a}</span><h2>Developer ${a}</h2><p>Wants to edit the file containing the status update function.</p><div class="action-row">${button('CLAIM','Claim work scope',a,'primary')}${state.lease===a?button('RELEASE','Release scope'):''}</div></article>`).join('')}</div>${state.claimMessage?flag(state.claimMessage.text,state.claimMessage.kind==='prepared'?'good':'warn'):flag('Claim the scope as contributor A, then try as contributor B.')}<div class="role-note"><strong>Why is this useful?</strong><p>A.R.I.A. tracks assignments, permissions and overlapping file scopes. In collaborative mode, a local coordinator manages the shared state.</p></div><p class="screen-note">This is an interactive model of the rule. GitHub is not connected; live collaboration requires separate acceptance testing.</p>`;}
  function featureCards(){const q=query.toLocaleLowerCase('en');return data.features.map((f,i)=>({f,i})).filter(({f})=>[f.title,f.benefit,...f.items].join(' ').toLocaleLowerCase('en').includes(q)).map(({f,i})=>`<button type="button" class="feature-card" data-action="FEATURE" data-value="${i}"><span>0${i+1}</span><h2>${f.title}</h2><p>${f.benefit}</p><strong>Explore capabilities →</strong></button>`).join('')||'<p class="empty-search">No features match your search.</p>';}
  function functionsView(){return intro('FEATURES AND BENEFITS','What does A.R.I.A. do for a project?','Open a feature, see its benefit and go to the related action in the demo.')+`<label class="search"><span>Find a feature</span><input id="feature-search" type="search" placeholder="For example: context, team, checks" value="${esc(query)}" autocomplete="off"></label><div class="feature-grid" id="feature-list">${featureCards()}</div>`;}
  function render(){
    document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===state.view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
    const demo=state.view==='demo';
    $('#scenario-rail').hidden=!demo;$('#footer-nav').hidden=!demo;$('#workspace').classList.toggle('wide',!demo);
    $('#step-nav').innerHTML=steps.map((name,i)=>`<button type="button" data-action="STEP" data-value="${i}" ${state.step===i?'aria-current="step"':''}><span>${String(i+1).padStart(2,'0')}</span><strong>${name}</strong><small>${state.visited.includes(i)&&i!==state.step?'•':''}</small></button>`).join('');
    $('#screen').innerHTML=demo?stageView():state.view==='about'?aboutView():state.view==='team'?teamView():functionsView();
    if(demo&&state.step===2){const depths={quick:['Quick','A local change with limited risk. This is the mode used in the recorded example.'],standard:['Standard','A change affecting several related parts. A.R.I.A. records requirements, tasks and acceptance criteria before the code is changed.'],deep:['Deep','A complex change with significant risks. The plan and checks cover dependencies and relevant failure scenarios.']};$('#screen').insertAdjacentHTML('beforeend',`<article class="depth-panel"><div><span class="eyebrow">WORK DEPTH</span><div class="segmented">${Object.entries(depths).map(([id,v])=>button('DEPTH',v[0],id,state.depth===id?'active':'')).join('')}</div></div><div><h2>${depths[state.depth][0]} mode</h2><p>${depths[state.depth][1]}</p><span class="small">This selector explains the workflow options. It does not change the recorded run.</span></div></article>`);}
    $('#screen').scrollTop=0;
    $('#step-counter').textContent=`${state.step+1} / 6`;$('#prev-step').disabled=state.step===0;
    $('#next-step').textContent=state.step===5?'Explore features →':state.step===0&&!state.taskLocked?'Save criteria → next':state.step===2&&!state.planReady?'Save plan → next':'Next →';
    if(demo&&state.step===5&&state.decision){const d=state.decision;let action;if(d.kind==='prepared')action=button('EDIT','Try changing the verified file','','secondary',state.revision!==1);else if(!state.taskLocked)action=button('GO','Save criteria',0,'primary');else if(!state.planReady)action=button('GO','Save the plan',2,'primary');else if(state.revision===2)action=button('RESTORE','Restore the verified version','','primary');else if(!state.check)action=button('GO','Open checks',4,'primary');else action=button('GO','Go to the fix',3,'primary');$('.decision-panel').insertAdjacentHTML('beforeend',`<div class="action-row">${action}</div>`);}
    $('#progress-label').textContent=`Step ${state.step+1} of 6`;$('#progress-fill').style.width=`${(state.step+1)/6*100}%`;
    $('#journal-count').textContent=state.history.length;
    $('#footer-note').textContent=demo?'Workflow model · checks from a recorded A.R.I.A. run':state.view==='team'?'Teamwork model · GitHub is not connected':'Local HTML demo · evidence available offline';
  }
  function modal(title,body){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;const d=$('#info-dialog');if(!d.open)d.showModal();}
  function materials(){modal('Evidence from the recorded run',`<p>The A.R.I.A. 1.5.5 core checked the module on October 4, 2026. These records are included in the demo and available offline.</p><div class="artifact-tabs">${button('ARTIFACT','Before the fix','before')}${button('ARTIFACT','After the fix','after')}${button('ARTIFACT','Check record','receipt')}${button('ARTIFACT','Scope and limits','limits')}</div><div id="artifact-body">${artifact('after')}</div>`);}
  function artifact(type){if(type==='limits')return '<h3>What was verified</h3><p>The failed permission check, the successful check of the fix, and rejection after the verified file was changed.</p><h3>Configuration</h3><p>Core 1.5.5; a temporary Python module; a compatible 1.4 profile in shadow mode. The reproduction script applies the code fix.</p><p>This run does not verify the complete signed 1.5.5 workflow, a live AI agent, independent review or live GitHub integration.</p>';
    if(type==='receipt')return `<h3>Successful check record</h3><pre>${esc(JSON.stringify(proof.receipt,null,2))}</pre><h3>Rejection after the file changed</h3><pre>${esc(JSON.stringify(proof.summary,null,2))}</pre>`;
    return `<h3>${type==='before'?'Initial version':'Fixed version'}</h3><pre>${esc(type==='before'?proof.beforeCode:proof.afterCode)}</pre><h3>Exact check output</h3><pre>${esc(type==='before'?proof.beforeOutput:proof.afterOutput)}</pre>`;}
  function feature(i){const f=data.features[i];if(!f)return;const go=[1,0,2,'team',2,4,5,'team',5][i];modal(f.title,`<p class="modal-lead">${f.benefit}</p><ul class="plain-list">${f.items.map(v=>`<li>${v}</li>`).join('')}</ul>${f.note?flag(f.note):''}<div class="action-row">${button('GO',go==='team'?'Try teamwork':'Open the related stage',go,'primary')}<a class="link-button" href="https://github.com/s41-i42-5va5/ARIA/blob/v1.5.5/${f.source}" target="_blank" rel="noopener noreferrer">Source on GitHub ↗</a></div><p class="small">The external link requires internet access. The main demo runs locally.</p>`);}
  function journal(){modal('Demo log',`<p>Your actions in the HTML demo are recorded here. This is the demo log, not an exported A.R.I.A. project history.</p>${state.history.length?`<ol class="journal">${state.history.map(h=>`<li><span>${h.number}</span>${esc(h.text)}</li>`).join('')}</ol>`:'<p class="empty-search">No actions yet. Start by saving the acceptance criteria.</p>'}`);}
  function handleAction(action,value){
    if(action==='MATERIALS')return materials();if(action==='FEATURE')return feature(Number(value));
    if(action==='ARTIFACT'){$('#artifact-body').innerHTML=artifact(value);return;}
    if(action==='GO'){if($('#info-dialog').open)$('#info-dialog').close();return dispatch(value==='team'?{type:'VIEW',value:'team'}:{type:'STEP',value:Number(value)});}
    dispatch({type:action,value});
  }
  document.addEventListener('click',event=>{const b=event.target.closest('[data-action]');if(b&&!b.disabled){const action=b.dataset.action,value=b.dataset.value;handleAction(action,value);if(!$('#info-dialog').open){const replacement=Array.from(document.querySelectorAll('[data-action]')).find(c=>c.dataset.action===action&&c.dataset.value===value);if(replacement)replacement.focus({preventScroll:true});else $('#screen').focus({preventScroll:true});}}});
  document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>dispatch({type:'VIEW',value:b.dataset.view})));
  $('#brand-home').addEventListener('click',event=>{event.preventDefault();dispatch({type:'VIEW',value:'demo'});});
  $('#prev-step').addEventListener('click',()=>dispatch({type:'STEP',value:state.step-1}));
  $('#next-step').addEventListener('click',()=>{if(state.step===0&&!state.taskLocked)state=engine.reduce(state,{type:'LOCK_TASK'});if(state.step===2&&!state.planReady)state=engine.reduce(state,{type:'PLAN'});dispatch(state.step===5?{type:'VIEW',value:'functions'}:{type:'STEP',value:state.step+1});});
  $('#reset-demo').addEventListener('click',()=>dispatch({type:'RESET'}));
  $('#open-journal').addEventListener('click',journal);$('#close-dialog').addEventListener('click',()=>$('#info-dialog').close());
  $('#info-dialog').addEventListener('click',event=>{if(event.target===$('#info-dialog'))$('#info-dialog').close();});
  $('#screen').addEventListener('input',event=>{if(event.target.id==='feature-search'){query=event.target.value;$('#feature-list').innerHTML=featureCards();}});
  $('#fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{const t=$('#toast');t.hidden=false;t.textContent='Fullscreen mode is unavailable in this viewer.';setTimeout(()=>t.hidden=true,3500);}});
  document.addEventListener('fullscreenchange',()=>$('#fullscreen').textContent=document.fullscreenElement?'Exit fullscreen ⤢':'Fullscreen ⤢');
  document.addEventListener('keydown',event=>{if(state.view!=='demo'||$('#info-dialog').open||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if(event.key==='ArrowRight'){event.preventDefault();dispatch({type:'STEP',value:state.step+1});}if(event.key==='ArrowLeft'){event.preventDefault();dispatch({type:'STEP',value:state.step-1});}});
  render();
})();
